

disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - multiple_closures_with_trailing_closure
  - nesting

opt_in_rules:
  - empty_count
  - missing_docs
  - array_init

line_length:
  warning: 350
  error: 400
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 800

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 2
  max_length:
    warning: 50
    error: 70
  excluded: ["id", "y", "x"]

cyclomatic_complexity:
  warning: 15
  error: 20

